"""
Domain entities — pure dataclasses with zero external dependencies.

These represent the core business objects of the marketplace analytics domain.
Every entity is immutable, hashable, and self-validating.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional


@dataclass(frozen=True)
class Order:
    """A single order line item from any marketplace."""

    order_id: str
    order_status: str
    product_name: str
    product_sku: Optional[str]
    variation: Optional[str]
    quantity: int
    price: Decimal
    total_amount: Decimal
    buyer_name: str
    buyer_username: str
    city: str
    province: str
    shipping_provider: Optional[str]
    shipping_method: Optional[str]
    shipping_cost: Decimal
    payment_method: str
    order_date: Optional[str]  # ISO-8601
    payment_date: Optional[str]
    shipping_date: Optional[str]
    voucher_seller: Decimal = Decimal("0")
    voucher_shopee: Decimal = Decimal("0")
    cancellation_reason: Optional[str] = None
    marketplace: str = "shopee"


@dataclass(frozen=True)
class Customer:
    """Customer profile aggregated across orders."""

    buyer_username: str
    buyer_name: str
    first_order_date: Optional[str] = None
    last_order_date: Optional[str] = None
    total_orders: int = 0
    total_revenue: Decimal = Decimal("0")
    total_products: int = 0
    city: Optional[str] = None
    province: Optional[str] = None


@dataclass(frozen=True)
class Product:
    """Product master data."""

    product_name: str
    product_sku: Optional[str] = None
    category: Optional[str] = None
    unit_price: Decimal = Decimal("0")
    total_quantity_sold: int = 0
    total_revenue: Decimal = Decimal("0")
    order_count: int = 0


@dataclass(frozen=True)
class City:
    """City-level geographic entity."""

    name: str
    province: str
    orders: int = 0
    customers: int = 0
    revenue: Decimal = Decimal("0")
    repeat_customers: int = 0
    top_product: Optional[str] = None
    growth_rate: Optional[float] = None


@dataclass(frozen=True)
class Province:
    """Province-level geographic entity."""

    name: str
    orders: int = 0
    customers: int = 0
    revenue: Decimal = Decimal("0")
    contribution_pct: float = 0.0
    growth_rate: Optional[float] = None


@dataclass(frozen=True)
class Payment:
    """Payment method snapshot."""

    method: str
    order_count: int = 0
    revenue: Decimal = Decimal("0")
    customer_count: int = 0
    top_region: Optional[str] = None


@dataclass(frozen=True)
class Shipping:
    """Shipping provider performance."""

    provider: str
    method: Optional[str] = None
    order_count: int = 0
    total_cost: Decimal = Decimal("0")
    avg_cost: Decimal = Decimal("0")


@dataclass(frozen=True)
class Cancellation:
    """Cancellation analytics record."""

    order_id: str
    reason: Optional[str] = None
    product_name: Optional[str] = None
    city: Optional[str] = None
    province: Optional[str] = None
    total_amount: Decimal = Decimal("0")
    order_date: Optional[str] = None


@dataclass(frozen=True)
class Insight:
    """A hidden insight or recommendation generated by the analytics engine."""

    type: str  # InsightType value
    title: str
    description: str
    metric_value: Optional[float] = None
    dimension: Optional[str] = None  # e.g. city name, product name
    recommendation: Optional[str] = None
    priority: str = "medium"  # high / medium / low
